<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABCProperties.Domain\ABCProperties.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Properties\" />
  </ItemGroup>

</Project>
